export interface TourOption {
  name: string;
  price: number;
  rPoints?: number;
  nonRefundable?: boolean;
  cancellation?: string;
}

export interface Tour {
  id: number;
  name: string;
  recommended?: boolean;
  superSaver?: boolean;
  cancellation: string;
  reviews: number;
  price: number;
  rPoints?: number;
  category: string;
  options: TourOption[];
}

export interface CartItem {
  tourId: number;
  tourName: string;
  optionName: string;
  transferOption: string;
  date: string;
  adults: number;
  children: number;
  infants: number;
  unitPrice: number;
  totalPrice: number;
  rPoints: number;
}

export const CATEGORIES = [
  "Sightseeing Tours",
  "Culture and Attractions",
  "Adventure Tours",
  "Burj Khalifa Tickets",
  "Dhow Cruise",
  "Food and Beverages",
  "Theme Parks",
  "Transfers",
  "Events and Occasions",
  "City Tours",
  "Nature and Wildlife",
  "Water Activities",
  "Cruise and Boat Tours",
  "Desert Safari Tours",
  "Airport Transfers",
  "Water Parks",
  "Fun and games",
  "Premium Tours",
  "Hop on Hop off Bus Dubai",
  "Burj Al Arab Tours",
  "Yacht Charter",
  "Camel and Horse Riding",
  "Hot Air Balloon",
  "Limousine Tours",
  "Atlantis Hotel Tours",
  "Helicopter Tours",
];

export const DESTINATIONS = [
  "UAE / Dubai",
  "Thailand",
  "Singapore",
  "United Kingdom",
  "USA",
  "Maldives",
  "Bali",
  "Sri Lanka",
  "Turkey",
  "Malaysia",
  "Abu Dhabi",
  "Oman",
  "Egypt",
  "Japan",
  "Australia",
];

export const TOURS: Tour[] = [
  {
    id: 1,
    name: "Dhow Cruise Dinner - Creek",
    recommended: true,
    cancellation: "Free Cancellation 24 hours Prior",
    reviews: 250,
    price: 936.67,
    category: "Dhow Cruise",
    options: [
      { name: "Standard Dhow Cruise", price: 936.67, rPoints: 0 },
      { name: "Premium Dhow Cruise", price: 1250, rPoints: 100 },
    ],
  },
  {
    id: 2,
    name: "Play DXB Dubai",
    cancellation: "Free Cancellation 24 hours Prior",
    reviews: 90,
    price: 4050.48,
    rPoints: 200,
    category: "Fun and games",
    options: [{ name: "General Entry", price: 4050.48, rPoints: 200 }],
  },
  {
    id: 3,
    name: "Yas Island Theme Park Tickets",
    cancellation: "Yas Island Cancellation Policy",
    reviews: 3,
    price: 8936.37,
    rPoints: 1000,
    category: "Theme Parks",
    options: [
      {
        name: "YAS Island 2 park pass",
        price: 8936.37,
        rPoints: 1000,
        nonRefundable: true,
      },
      { name: "Warner Bros Day Pass", price: 7366.81, rPoints: 500 },
      {
        name: "Yas waterworld Day pass - OD",
        price: 5721.3,
        rPoints: 3000,
        nonRefundable: true,
      },
      { name: "YAS Island 3 park pass", price: 10708.45, rPoints: 600 },
      { name: "YAS Island 4 park pass", price: 12531.17, rPoints: 200 },
      { name: "SEAWORLD day pass", price: 7974.38, rPoints: 500 },
      { name: "Ferrariworld Day Pass", price: 7366.81, rPoints: 500 },
      {
        name: "Ferrari World Entry Ticket",
        price: 7290.86,
        rPoints: 200,
        cancellation: "Free Cancellation 48 hours Prior",
      },
      { name: "Warner Bros Fast Track Ticket", price: 7214.92, rPoints: 0 },
      { name: "Yas Water World Fast Track Ticket", price: 4683.37, rPoints: 0 },
      { name: "Ferrari World Fast Track Ticket", price: 5949.14, rPoints: 0 },
      { name: "Sea World Fast Track Ticket", price: 7214.92, rPoints: 0 },
      {
        name: "Yas Island Any One Park Meal Voucher",
        price: 1392.35,
        rPoints: 0,
      },
      { name: "Sea World Meal Voucher", price: 1645.51, rPoints: 0 },
      {
        name: "Yas 1 day 2 park Ticket - Dated Tickets",
        price: 7974.38,
        rPoints: 0,
      },
    ],
  },
  {
    id: 4,
    name: "Desert Safari",
    recommended: true,
    cancellation: "Free Cancellation 24 hours Prior",
    reviews: 2100,
    price: 2784.7,
    rPoints: 800,
    category: "Desert Safari Tours",
    options: [
      { name: "Standard Desert Safari", price: 2784.7, rPoints: 800 },
      { name: "Premium Desert Safari", price: 3594.8, rPoints: 700 },
    ],
  },
  {
    id: 5,
    name: "IMG Worlds of Adventure",
    recommended: true,
    cancellation: "Non Refundable",
    reviews: 258,
    price: 4202.37,
    rPoints: 100,
    category: "Theme Parks",
    options: [
      {
        name: "General Admission",
        price: 4202.37,
        rPoints: 100,
        nonRefundable: true,
      },
    ],
  },
  {
    id: 6,
    name: "Dubai City Tour",
    recommended: true,
    cancellation: "Free Cancellation 24 hours Prior",
    reviews: 2688,
    price: 1189.83,
    category: "City Tours",
    options: [
      { name: "Half Day City Tour", price: 1189.83, rPoints: 0 },
      { name: "Full Day City Tour", price: 2404.97, rPoints: 500 },
    ],
  },
  {
    id: 7,
    name: "Dhow Cruise Dinner - Marina",
    recommended: true,
    cancellation: "Free Cancellation 24 hours Prior",
    reviews: 419,
    price: 2025.24,
    rPoints: 500,
    category: "Dhow Cruise",
    options: [{ name: "Standard", price: 2025.24, rPoints: 500 }],
  },
  {
    id: 8,
    name: "Global Village Dubai",
    recommended: true,
    cancellation: "Non Refundable",
    reviews: 121,
    price: 632.89,
    category: "Culture and Attractions",
    options: [
      { name: "General Entry", price: 632.89, rPoints: 0, nonRefundable: true },
    ],
  },
  {
    id: 9,
    name: "Abu Dhabi City Tour",
    recommended: true,
    cancellation: "Free Cancellation 24 hours Prior",
    reviews: 1553,
    price: 2708.76,
    rPoints: 2500,
    category: "City Tours",
    options: [
      { name: "Shared Tour", price: 2708.76, rPoints: 2500 },
      { name: "Private Tour", price: 5000, rPoints: 3000 },
    ],
  },
  {
    id: 10,
    name: "Abu Dhabi City Tour With Ferrari World",
    recommended: true,
    cancellation: "Free Cancellation 48 hours Prior",
    reviews: 258,
    price: 7999.7,
    category: "City Tours",
    options: [{ name: "Shared", price: 7999.7, rPoints: 0 }],
  },
  {
    id: 11,
    name: "Ski Dubai Tickets",
    recommended: true,
    cancellation: "Non Refundable",
    reviews: 127,
    price: 4936.52,
    rPoints: 200,
    category: "Water Parks",
    options: [
      {
        name: "Snow Classic",
        price: 4936.52,
        rPoints: 200,
        nonRefundable: true,
      },
      { name: "Snow Plus", price: 6500, rPoints: 300, nonRefundable: true },
    ],
  },
  {
    id: 12,
    name: "Full Day Explore Dubai City Tour",
    recommended: true,
    cancellation: "Free Cancellation 24 hours Prior",
    reviews: 354,
    price: 2404.97,
    rPoints: 500,
    category: "City Tours",
    options: [{ name: "Full Day Tour", price: 2404.97, rPoints: 500 }],
  },
  {
    id: 13,
    name: "Big Bus Tour Dubai",
    recommended: true,
    cancellation: "Free Cancellation 24 hours Prior",
    reviews: 135,
    price: 3873.27,
    category: "Hop on Hop off Bus Dubai",
    options: [
      { name: "24h Pass", price: 3873.27, rPoints: 0 },
      { name: "48h Pass", price: 5500, rPoints: 0 },
    ],
  },
  {
    id: 14,
    name: "Atlantis Aquaventure Waterpark",
    recommended: true,
    cancellation: "Non Refundable",
    reviews: 302,
    price: 2582.18,
    rPoints: 1000,
    category: "Water Parks",
    options: [
      {
        name: "General Entry",
        price: 2582.18,
        rPoints: 1000,
        nonRefundable: true,
      },
    ],
  },
  {
    id: 15,
    name: "Dubai Aquarium and Underwater Zoo",
    cancellation: "Free Cancellation 24 hours Prior",
    reviews: 173,
    price: 3291.01,
    rPoints: 200,
    category: "Culture and Attractions",
    options: [{ name: "Tunnel & Zoo", price: 3291.01, rPoints: 200 }],
  },
  {
    id: 16,
    name: "Dubai Parks and Resorts",
    cancellation: "Non Refundable",
    reviews: 162,
    price: 5544.09,
    rPoints: 200,
    category: "Theme Parks",
    options: [
      {
        name: "1 Day 1 Park",
        price: 5544.09,
        rPoints: 200,
        nonRefundable: true,
      },
    ],
  },
  {
    id: 17,
    name: "Photo Pass for Dubai attractions",
    cancellation: "Free Cancellation 24 hours Prior",
    reviews: 2,
    price: 506.31,
    rPoints: 100,
    category: "Sightseeing Tours",
    options: [{ name: "Photo Pass", price: 506.31, rPoints: 100 }],
  },
  {
    id: 18,
    name: "Yacht Party at Dubai Marina",
    cancellation: "Free Cancellation 24 hours Prior",
    reviews: 8,
    price: 4860.57,
    rPoints: 100,
    category: "Yacht Charter",
    options: [{ name: "2hr Party", price: 4860.57, rPoints: 100 }],
  },
  {
    id: 19,
    name: "Dream Boats Floating Cafe",
    cancellation: "Free Cancellation 72 hours Prior",
    reviews: 1,
    price: 11138.82,
    rPoints: 1000,
    category: "Cruise and Boat Tours",
    options: [
      { name: "Floating Cafe Experience", price: 11138.82, rPoints: 1000 },
    ],
  },
  {
    id: 20,
    name: "Dubai Dolphinarium Open Dated Tickets",
    recommended: true,
    cancellation: "Non Refundable",
    reviews: 1,
    price: 2187.01,
    category: "Nature and Wildlife",
    options: [
      {
        name: "Open Dated Ticket",
        price: 2187.01,
        rPoints: 0,
        nonRefundable: true,
      },
    ],
  },
  {
    id: 21,
    name: "Hatta Wadi Activities",
    cancellation: "Free Cancellation 24 hours Prior",
    reviews: 37,
    price: 582.26,
    category: "Adventure Tours",
    options: [{ name: "Basic Activities", price: 582.26, rPoints: 0 }],
  },
  {
    id: 22,
    name: "Dubai Fountain Show and Lake Ride",
    recommended: true,
    cancellation: "Non Refundable",
    reviews: 150,
    price: 607.57,
    category: "Sightseeing Tours",
    options: [
      {
        name: "Fountain Show + Lake Ride",
        price: 607.57,
        rPoints: 0,
        nonRefundable: true,
      },
    ],
  },
  {
    id: 23,
    name: "Dubai Frame",
    cancellation: "Non Refundable",
    reviews: 595,
    price: 1240.46,
    rPoints: 200,
    category: "Culture and Attractions",
    options: [
      {
        name: "General Entry",
        price: 1240.46,
        rPoints: 200,
        nonRefundable: true,
      },
    ],
  },
  {
    id: 24,
    name: "Museum of the Future",
    cancellation: "Non Refundable",
    reviews: 124,
    price: 3822.64,
    rPoints: 600,
    category: "Culture and Attractions",
    options: [
      {
        name: "General Entry",
        price: 3822.64,
        rPoints: 600,
        nonRefundable: true,
      },
    ],
  },
  {
    id: 25,
    name: "Hot Air Balloon Dubai",
    cancellation: "Free Cancellation 48 hours Prior",
    reviews: 139,
    price: 12151.44,
    category: "Hot Air Balloon",
    options: [
      { name: "Shared Balloon", price: 12151.44, rPoints: 0 },
      { name: "With Breakfast", price: 14682.99, rPoints: 0 },
      { name: "With Refreshments", price: 12151.44, rPoints: 0 },
    ],
  },
  {
    id: 26,
    name: "Skydive Dubai",
    cancellation: "Non Refundable",
    reviews: 121,
    price: 53441.01,
    rPoints: 2000,
    category: "Adventure Tours",
    options: [
      {
        name: "Tandem Skydive",
        price: 53441.01,
        rPoints: 2000,
        nonRefundable: true,
      },
    ],
  },
  {
    id: 27,
    name: "Dubai Helicopter Tours",
    cancellation: "Non Refundable",
    reviews: 102,
    price: 15290.56,
    rPoints: 2400,
    category: "Helicopter Tours",
    options: [
      {
        name: "12 min tour",
        price: 15290.56,
        rPoints: 2400,
        nonRefundable: true,
      },
      { name: "25 min tour", price: 25000, rPoints: 3000, nonRefundable: true },
    ],
  },
  {
    id: 28,
    name: "Dinner in the Sky",
    recommended: true,
    cancellation: "Non Refundable",
    reviews: 152,
    price: 17189.22,
    rPoints: 200,
    category: "Food and Beverages",
    options: [
      {
        name: "Standard Dinner",
        price: 17189.22,
        rPoints: 200,
        nonRefundable: true,
      },
    ],
  },
  {
    id: 29,
    name: "Desert Buggy Driving Experience",
    cancellation: "Free Cancellation 24 hours Prior",
    reviews: 414,
    price: 9619.89,
    category: "Adventure Tours",
    options: [
      { name: "1hr Buggy Drive", price: 9619.89, rPoints: 0 },
      { name: "2hr Buggy Drive", price: 15000, rPoints: 0 },
    ],
  },
  {
    id: 30,
    name: "Camel Riding",
    recommended: true,
    cancellation: "Free Cancellation 24 hours Prior",
    reviews: 132,
    price: 10252.78,
    category: "Camel and Horse Riding",
    options: [{ name: "30min Camel Ride", price: 10252.78, rPoints: 0 }],
  },
  {
    id: 31,
    name: "Scuba Diving Tour",
    recommended: true,
    cancellation: "Free Cancellation 60 hours Prior",
    reviews: 119,
    price: 6582.03,
    category: "Water Activities",
    options: [
      { name: "Beginner Dive", price: 6582.03, rPoints: 0 },
      { name: "Advanced Dive", price: 9000, rPoints: 0 },
    ],
  },
  {
    id: 32,
    name: "Dubai Parasailing",
    cancellation: "Free Cancellation 24 hours Prior",
    reviews: 112,
    price: 7189.6,
    category: "Water Activities",
    options: [{ name: "Parasailing", price: 7189.6, rPoints: 0 }],
  },
  {
    id: 33,
    name: "Luxury yacht rental Dubai",
    recommended: true,
    cancellation: "Free Cancellation 48 hours Prior",
    reviews: 81,
    price: 7594.65,
    rPoints: 2000,
    category: "Yacht Charter",
    options: [
      { name: "2hr Yacht", price: 7594.65, rPoints: 2000 },
      { name: "4hr Yacht", price: 14000, rPoints: 3000 },
    ],
  },
  {
    id: 34,
    name: "Miracle Garden Dubai",
    recommended: true,
    cancellation: "Non Refundable",
    reviews: 211,
    price: 2025.24,
    rPoints: 500,
    category: "Nature and Wildlife",
    options: [
      {
        name: "General Entry",
        price: 2025.24,
        rPoints: 500,
        nonRefundable: true,
      },
    ],
  },
  {
    id: 35,
    name: "Kayaking Experience in Dubai",
    recommended: true,
    cancellation: "Free Cancellation 24 hours Prior",
    reviews: 390,
    price: 1645.51,
    rPoints: 200,
    category: "Water Activities",
    options: [{ name: "1hr Kayak", price: 1645.51, rPoints: 200 }],
  },
  {
    id: 36,
    name: "Burj Khalifa Tickets",
    cancellation: "Non Refundable",
    reviews: 8,
    price: 4607.42,
    rPoints: 1200,
    category: "Burj Khalifa Tickets",
    options: [
      {
        name: "At The Top (Level 124)",
        price: 4607.42,
        rPoints: 1200,
        nonRefundable: true,
      },
      {
        name: "At The Top SKY (Level 148)",
        price: 7500,
        rPoints: 1500,
        nonRefundable: true,
      },
    ],
  },
  {
    id: 37,
    name: "Premium Desert Safari",
    cancellation: "Free Cancellation 24 hours Prior",
    reviews: 585,
    price: 3594.8,
    rPoints: 700,
    category: "Desert Safari Tours",
    options: [{ name: "Premium Safari", price: 3594.8, rPoints: 700 }],
  },
  {
    id: 38,
    name: "iFly Dubai",
    cancellation: "Non Refundable",
    reviews: 492,
    price: 3620.12,
    rPoints: 800,
    category: "Adventure Tours",
    options: [
      {
        name: "2 Flight Package",
        price: 3620.12,
        rPoints: 800,
        nonRefundable: true,
      },
    ],
  },
  {
    id: 39,
    name: "Sunrise Safari Dubai",
    cancellation: "Free Cancellation 24 hours Prior",
    reviews: 206,
    price: 10958.06,
    category: "Desert Safari Tours",
    options: [{ name: "Sunrise Safari", price: 10958.06, rPoints: 0 }],
  },
  {
    id: 40,
    name: "Morning Safari",
    cancellation: "Free Cancellation 24 hours Prior",
    reviews: 387,
    price: 2151.82,
    category: "Desert Safari Tours",
    options: [{ name: "Morning Safari", price: 2151.82, rPoints: 0 }],
  },
  {
    id: 41,
    name: "Private Limousine Rental Dubai",
    cancellation: "Free Cancellation 48 hours Prior",
    reviews: 170,
    price: 12657.75,
    category: "Limousine Tours",
    options: [
      { name: "3hr Limousine", price: 12657.75, rPoints: 0 },
      { name: "6hr Limousine", price: 20000, rPoints: 0 },
    ],
  },
  {
    id: 42,
    name: "Dolphin Bay Atlantis",
    recommended: true,
    cancellation: "Free Cancellation 24 hours Prior",
    reviews: 46,
    price: 14657.67,
    rPoints: 200,
    category: "Atlantis Hotel Tours",
    options: [{ name: "Dolphin Encounter", price: 14657.67, rPoints: 200 }],
  },
  {
    id: 43,
    name: "Guided Inside Burj Al Arab Tour",
    cancellation: "Non Refundable",
    reviews: 77,
    price: 6506.08,
    rPoints: 200,
    category: "Burj Al Arab Tours",
    options: [
      {
        name: "Inside Tour",
        price: 6506.08,
        rPoints: 200,
        nonRefundable: true,
      },
    ],
  },
  {
    id: 44,
    name: "La Perle by Dragone Dubai",
    cancellation: "Non Refundable",
    reviews: 112,
    price: 5037.78,
    rPoints: 200,
    category: "Events and Occasions",
    options: [
      {
        name: "Standard Seat",
        price: 5037.78,
        rPoints: 200,
        nonRefundable: true,
      },
      { name: "VIP Seat", price: 8000, rPoints: 400, nonRefundable: true },
    ],
  },
  {
    id: 45,
    name: "Deep Sea Fishing",
    cancellation: "Free Cancellation 72 hours Prior",
    reviews: 216,
    price: 25821.8,
    category: "Water Activities",
    options: [
      { name: "4hr Fishing", price: 25821.8, rPoints: 0 },
      { name: "8hr Fishing", price: 40000, rPoints: 0 },
    ],
  },
];

export const SUPER_SAVERS = [
  {
    id: 101,
    name: "AYA Universe and Dubai Frame Combo Tickets",
    reviews: 736,
    price: 3341.65,
  },
  {
    id: 102,
    name: "IMG Worlds of Adventure + The View at The Palm Dubai",
    reviews: 260,
    price: 5974.46,
  },
  {
    id: 103,
    name: "Dubai Frame + Dubai Aquarium and Underwater Zoo",
    reviews: 768,
    price: 4354.27,
  },
  {
    id: 104,
    name: "Dubai Aquarium and Underwater Zoo + Green Planet",
    reviews: 268,
    price: 4200.0,
  },
];

export const INR = (n: number) =>
  `₹${n.toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
